### ISSUE TITLE
Convert library to typescript 

### ISSUE THREAD

**Issue by kevbrowndev** [apache/incubator-flagon-useralejs#235]
Are you open to the idea of converting the library to typescript? If so I was thinking of giving it a go.

Here's some information on how one might convert a library to type script and why one might want to do it.
https://www.typescriptlang.org/docs/handbook/migrating-from-javascript.html

**Comment by kevbrowndev** [comment]
One possible benefit is that this could make it more convenient for those using userl to see possible parameters one can add to options. I believe converting to typescript would do that but don't hold me to it.

**Comment by poorejc** [comment]
Hi @kevbrowndev sorry missed this question. I have had some discussions with some folks about rel to some projects I'm doing. However, I haven't raised it with the community. I've had some UserALE users in the past ask for a JQuery version of UserALE as well. It's worth having that conversation, I think. However, way back when we actually supported 3 different versions of userale--user-ale (just a simple API), UserALE.js, and UserALEpyqt5 (for python apps). We quickly found that so many versions were difficult to maintain. I think we would need to think about whether the conversion would completely replace UserALE.js (UserALE.ts... i guess) or whether we'd end up needing to support two or more versions focused on webapps. My 02c

**Comment by kevbrowndev** [comment]
Thank you for considering the idea. 

I'm still just a Typescript dabbler, but my understanding is that the beauty of it is that ts code can be converted into whatever flavor of JavaScript is needed. Therefore only one version of UserAle, the typescript version, would be necessary. :)

Of course this wouldn't make sense if the primary contributors aren't comfortable with Typescript.

**Comment by kevbrowndev** [comment]
Looks like there isn't any interest in this.

**Comment by kevbrowndev** [comment]
No interest.

**Comment by brucearctor** [comment]
@kevbrowndev -- stronger types are generally helpful, and I'd suggest typescript > javascript [ at least in that regards ].  

I also don't think that it's a heavy lift for a competent [ javascript ] programmer to be proficient in typescript.  

But, since this would be a new/significant thing that the community would need to support -- you'd likely want to take this to the mailing list [ most probably are not following all/individual github issues ]. 

Also, TBD on how many others want to help develop it, but ultimately would need community support for adoption.

**Comment by kevbrowndev** [comment]
Thank you for your reply. I've heard from a couple of people and it seems
like it doesn't have widespread support I'm on contributors. I don't think
it's a high priority but maybe down the line!

**Comment by poorejc** [comment]
@kevbrowndev definitely interest but my team and I are biting off a few other things first (also limited typescript experience on my end). IF we can rally some contributors here, I'm happy to put in elbow grease in testing and getting this into release management, at minimum?

Just because it's a `not yet`, I don't think we need to close this. Happy to reopen to see if we get other nibbles... any objections?

**Comment by poorejc** [comment]
added help wanted flag.
